name: lokix-test
services:
  crawler:
    restart: on-failure
    build:
      context: .
      dockerfile: Dockerfile
      target: run-test-stage
  
  db:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: crawler
      MONGO_INITDB_ROOT_PASSWORD: crawler-pwd
    volumes:
      - crawler-volume:/var/lib/mongo